### PR TITLE
Update CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by GopalGupta8216**

### CODE REVIEW

**Comment by GopalGupta8216** [comment]
Is it alright now

**Review by algomaster99 — CHANGES_REQUESTED** [review]
@GopalGupta8216 you need to add a link to the hosted recruitment website, not your GitHub profile.

**Comment by GopalGupta8216** [comment]
@algomaster99 I had done the required changes in branch gopal,so is there a need to make another PR

**Review by algomaster99 — CHANGES_REQUESTED** [review]
@GopalGupta8216 still not done. You have to put the link of your hosted assignment not your repository. See how others have done it.

**Comment by GopalGupta8216** [comment]
@algomaster99  Is it Finally done???

**Pull request merged**
